[build-system]
requires = [ "setuptools", "setuptools_scm" ]
build-backend = "setuptools.build_meta"

[project]
name = "rubin-sim"
description = "Scheduler, survey strategy analysis, and other simulation tools for Rubin Observatory."
license = { text = "GPL" }
classifiers = [ 
    "Intended Audience :: Science/Research",
    "License :: OSI Approved ::  GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Topic :: Scientific/Engineering :: Astronomy",
 ]
urls = {documentation = "https://jira.lsstcorp.org/secure/Dashboard.jspa", repository = "https://github.com/lsst/rubin_sim" }
dynamic = [ "version" ]

[project.scripts]
rs_download_data = "rubin_sim.data.rs_download_data:rs_download_data"
rs_download_sky = "rubin_sim.data.rs_download_sky:rs_download_sky"
addRun = "rubin_sim.maf.db.add_run:addRun"
ddf_dir = "rubin_sim.maf.ddf_dir:ddf_dir"
gather_summaries = "rubin_sim.maf.runComparison.gather_summaries:gather_summaries"
generate_ss = "rubin_sim.maf.generate_ss:generate_ss"
glance_dir = "rubin_sim.maf.glance_dir:glance_dir"
maf_night_report = "rubin_sim.maf.maf_night_report:maf_night_report"
metadata_dir = "rubin_sim.maf.metadata_dir:metadata_dir"
resultdb_combine = "rubin_sim.maf.runComparison.resultdb_combine:resultdb_combine"
run_moving_calc = "rubin_sim.maf.run_moving_calc:run_moving_calc"
run_moving_fractions = "rubin_sim.maf.run_moving_fractions:run_moving_fractions"
run_moving_join = "rubin_sim.maf.batches.run_moving_join:run_moving_join"
scimaf_dir = "rubin_sim.maf.scimaf_dir:scimaf_dir"
showMaf = "rubin_sim.maf.show_maf:showMaf"
addSeds = "rubin_sim.movingObjects.add_seds:add_seds"
generateCoefficients = "rubin_sim.movingObjects.generate_coefficients:generate_coefficients"
makeLSSTobs = "rubin_sim.movingObjects.make_lsst_obs:make_lsst_obs"

[project.optional-dependencies]
dev = [
  "documenteer[pipelines]",
]

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }

[tool.setuptools.packages.find]
where = [ "" ]

[tool.setuptools_scm]
write_to = "rubin_sim/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""

[tool.pytest.ini_options]
addopts = "--black --ignore-glob=*/version.py"
flake8-ignore = ["E133", "E203", "E226", "E228", "N802", "N803", "N806", "N812", "N813", "N815", "N816", "W503"]
flake8-max-line-length = 110
flake8-max-doc-length = 79
asyncio_mode = "auto"

[tool.mypy]
disallow_untyped_defs = "True"
ignore_missing_imports = "True"
exclude = "version.py"
